//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public string StudentID { get; set; }
        public string StudentRoll { get; set; }
        public string StudentName { get; set; }
        public string DepartmentName { get; set; }
        public string StudentAddress { get; set; }
        public string ContactTitle { get; set; }
        public string StudentEmail { get; set; }
    }
}
